OPENWEATHER_API_KEY = "ac3684dc683f072658f03f6b4a039e0f"
GROQ_API_KEY = "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"
PLANET_API_KEY = "PLAK8713d10a14e647e49b20d1c871799f46"
LLM_TEMP = 0.3